-- MySQL Script generated by MySQL Workbench
-- 03/14/16 09:21:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bintics.web
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bintics.web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bintics.web` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bintics.web` ;

-- -----------------------------------------------------
-- Table `bintics.web`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bintics.web`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  `timestamp` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bintics.web`.`users_profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bintics.web`.`users_profiles` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `first_name` VARCHAR(45) NULL COMMENT '',
  `last_name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`, `user_id`)  COMMENT '',
  INDEX `fk_users_profiles_users_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_users_profiles_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `bintics.web`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bintics.web`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bintics.web`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` NVARCHAR(45) NOT NULL COMMENT '',
  `timestamp` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bintics.web`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bintics.web`.`courses` (
  `name` VARCHAR(200) NOT NULL COMMENT '',
  `start_date` DATETIME NOT NULL COMMENT '',
  `group_id` INT NOT NULL COMMENT '',
  `cost` DECIMAL(10,0) NOT NULL DEFAULT 0 COMMENT '',
  `description` NVARCHAR(1000) NULL COMMENT '',
  `timestamp` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`name`, `start_date`)  COMMENT '',
  INDEX `fk_courses_groups1_idx` (`group_id` ASC)  COMMENT '',
  CONSTRAINT `fk_courses_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `bintics.web`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bintics.web`.`user_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bintics.web`.`user_courses` (
  `course_name` VARCHAR(200) NOT NULL COMMENT '',
  `course_start_date` DATETIME NOT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `timestamp` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`course_name`, `course_start_date`, `user_id`)  COMMENT '',
  INDEX `fk_courses_has_users_users1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_courses_has_users_courses1_idx` (`course_name` ASC, `course_start_date` ASC)  COMMENT '',
  CONSTRAINT `fk_courses_has_users_courses1`
    FOREIGN KEY (`course_name` , `course_start_date`)
    REFERENCES `bintics.web`.`courses` (`name` , `start_date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_has_users_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `bintics.web`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
